Fixed bug in image saver, modified gitignore, and added support for KDE
Muhimen123/tapetti pull request #4
Opened 2021-07-22 14:03 UTC by classPythonAddike

I modified the image saver and downloader functions, to use os.path.join()
I also added the image directory under data/ to the gitignore. I'm not sure if this will cause issues 😉 lmk if I should revert it

Finally I added support for KDE :partying_face: and it works fine on my machine

2021-07-22 16:49 UTC, Muhimen123 requested changes
One small fix.

2021-07-22 16:49 UTC, Muhimen123 commented on .gitignore
> +data/images/*
![image](https://user-images.githubusercontent.com/44261822/126676678-b2fdc479-f401-4a85-8df9-7c1c061a54b2.png)

I actually had this previously in the gitignore. But faced the same problem. Currently I can think of two fixes.

1. Keep the images folder
2. check if the file exists or not. If not, then create the file(and folder) first

Second one seems better imo. You think you can handle that?

2021-07-23 05:38 UTC, Muhimen123 commented
Friendly warning! I did some changes in `image_saver.py` for XFCE support. Make sure to re fork the repo to avoid conflict. 😉

2021-07-24 03:26 UTC, classPythonAddike commented
:+1: I will work on it in a while

2021-07-24 03:48 UTC, classPythonAddike commented
I'm not too good with github pr's, so I'll close this and create a new one with the changes :smile:

2021-07-24 03:48 UTC, closed without merging